######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 30 22:05:21 2010
######################################################################

TEMPLATE = app
TARGET = qtGUI 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageWidget.h
SOURCES += imageWidget.cpp qtGUI.cpp
