######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 5 17:26:38 2010
######################################################################

TEMPLATE = app
TARGET = meegotouchGUI
CONFIG += meegotouch 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mtwindow.h
SOURCES += meegotouchGUI.cpp mtwindow.cpp
