#!/bin/bash
if [ "$#" -eq 0 ];then
echo "Usage"
echo "cputest <indicator> <number>"
exit 0
fi

if [ "$#" -lt 2 ];then
    echo "Please input number"
else
    if [ "$1" == "audio" ] || [ "$1" == "video" ] || [ "$1" == "photo" ] \
    || [ "$1" == "browser" ] || [ "$1" == "idle" ]; then
        if [ "$1" == "audio" ] || [ "$1" == "video" ]; then
            ./appMon.py -p meego-qml,pul -c 40 -d5 -D &> /root/$1_appmon$2.log &
        elif [ "$1" == "browser" ]; then
            ./appMon.py -p meego-app,pul -c 40 -d5 -D &> /root/$1_appmon$2.log &
        elif [ "$1" == "photo" ]; then
            ./appMon.py -p meego-qml -c 40 -d5 -D &> /root/$1_appmon$2.log &
        elif [ "$1" == "idle" ]; then
            ./appMon.py -p appmon -c 40 -d5 -D &> /root/$1_appmon$2.log &
        fi
        ./sysmon -d5 -c20 & #> /root/$1_sysmon$2.log &
        sleep 250
        cp /tmp/sysmon_cpu.html /root/$1_sysmon_cpu$2.html
        
        echo "######This is appmon log######"
        cat /root/$1_appmon$2.log | sed -n '1,5p'
        #echo "######This is sysmon log######"
        #cat /root/$1_sysmon$2.log | 
        echo "Please check sysmon html log file at /root"
    else
        echo "Please input right indicator"
    fi
fi
